### ISSUE TITLE
[discuss] Is there a fair way to test waf? 

### ISSUE THREAD

**Issue by imfht** [wallarm/gotestwaf#117]
Hi :
    I'm  thinking gotestwaf is forced on test method (such as placeholder/encoders) and the test case is little.
    The waf provider can add rules for then. And it is not fair for other waf who didn't know this project.
    If all waf provider know the test case. all waf get reject rate 100%.
    Do you think is there a fair way to test waf and give it an grade?
Thanks!

**Comment by mendhak** [comment]
Because the nature of threats is always changing, the kinds of attacks that are performed is also changing. In other words it's an ever-growing, or ever-evolving list of attacks.  WAF vendors need to keep their rule-sets up to date, and not only that, this project needs to keep its rules up to date too.  It wouldn't be fair to end users (us) if neither of them kept their rules up to date, since we'd be getting an inaccurate rating and a false sense of security.    

For something like [SSLLabs](https://www.ssllabs.com/ssltest/), there is a rating but the case is different, that's an actual checklist to follow.
