### ISSUE TITLE
Missing content-type on parts of multipart requests?

### ISSUE THREAD

**Issue by dankegel** [wallarm/gotestwaf#140]
internal/payload/placeholder/htmlmultipartform.go doesn't know the content type of the bytes it is stuffing into the form,
so when the URL encoder is in use, it can't set the content byte to application/x-www-form-urlencoded, and the web server being probed won't url decode the bytes.

Is this intentional?  i.e. is gotestwaf targeting vulnerabilities where applications (perhaps unwisely) do their own additional urldecoding of the payload handed to it by the web server?

If this is a bug, it may be fixable by copying the source for the convenience function CreateFormField() and setting a content type as CreateFormFile does.

**Comment by svkirillov** [comment]
Hi!

The main reason that the part of a multipart request doesn't have a specific content type is because we don't know the type of the payload we are putting into the request. It can be JSON or XML without any encoding (plain encoder) or plain text payload with some encoding. The second reason is that our goal is to test a WAF, not a web app. And in this case, the missing content-type header is sort of a test for the WAF. So we only need a Content-Type header for the entire request, and we don't need a Content-Type header for a part.
