### ISSUE TITLE
Unable to create and email report

### ISSUE THREAD

**Issue by joyent-secops** [wallarm/gotestwaf#196]
When I finish running the gotestwaf using the following command:
docker run --network="host"^Cit -v ${PWD}/reports:/app/reports wallarm/gotestwaf --url=https://myweb.com

It can't create report and send emails.

Do you want to include payload details to the report? ([y/N]): y
INFO[0254] Export full report                            filename=reports/waf-evaluation-report-2023-March-24-08-43-43.pdf
Email to send the report (ENTER to skip): xxxxx@xxxxx.com
ERRO[0263] caught error in main function                 error="couldn't send report by email: Invalid information in report data"

I tested it in the centos 7 and ubuntu 20.04 (both running x86_64).

**Comment by svkirillov** [comment]
Hi!

Thank you for report!

The bug was in the CI/CD configuration. Due to the specifics of the default strategy of repository checkout in GitHub Actions, running `git describe` failed and the version string was empty, affecting report validation on the server.

Could you please pull the GoTestWAF again and check if everything works properly?

```sh
docker image rm wallarm/gotestwaf
docker pull wallarm/gotestwaf
docker run --rm wallarm/gotestwaf --version
```

If the output is `GoTestWAF v0.4.0`, you can try to run scanning again.

**Comment by whatthejay** [comment]
@svkirillov It works with the latest version - GoTestWAF v0.4.0.
Thank you.

**Comment by joyent-secops** [comment]
@svkirillov Thank you, it works fine with latest docker image - GoTestWAF v0.4.0.
